# Generated by Django 3.0.4 on 2020-07-05 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 7, 5, 11, 18, 22, 725947))),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogviews', to='blog.Blog')),
            ],
        ),
    ]
