# Generated by Django 3.0.4 on 2020-07-10 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_total',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 11, 35, 56, 150630)),
        ),
    ]
