# Generated by Django 3.0.4 on 2020-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
