# Generated by Django 3.0.4 on 2020-07-10 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200710_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='opening',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 11, 47, 43, 780443)),
        ),
    ]
