# Generated by Django 3.0.4 on 2020-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200720_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='ip',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='session',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
