# Generated by Django 3.0.4 on 2020-07-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200710_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 11, 48, 52, 252898)),
        ),
    ]
