# Generated by Django 3.0.4 on 2020-07-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200710_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
