# Generated by Django 3.0.4 on 2020-07-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200726_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='session',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
