# Generated by Django 3.0.9 on 2020-08-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200726_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Mtech', 'Mtech'), ('MBA', 'MBA'), ('UG-Medical', 'UG-Medical'), ('PG-Medical', 'PG-Medical'), ('Engineering', 'Engineering'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('All', 'All')], default='All', max_length=255),
        ),
    ]
