# Generated by Django 3.0.4 on 2020-07-11 15:24

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200710_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
