# Generated by Django 3.0.9 on 2020-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Mtech', 'Mtech'), ('MBA', 'MBA'), ('UG-Medical', 'UG-Medical'), ('PG-Medical', 'PG-Medical'), ('Engineering', 'Engineering'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('All', 'All'), ('Arts', 'Arts'), ('Updates', 'Updates')], default='All', max_length=255),
        ),
    ]
