# Generated by Django 3.0.4 on 2020-07-11 16:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200711_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='search',
            new_name='search_document',
        ),
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='blog_blog_search__46d1ce_gin'),
        ),
    ]
