# Generated by Django 3.0.9 on 2021-03-11 14:37

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201007_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
