# Generated by Django 3.0.4 on 2020-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200704_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='applied_for',
            field=models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('NEET-PG', 'NEET-PG'), ('CET', 'CET'), ('COMED-K', 'COMED-K'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
