# Generated by Django 3.0.4 on 2020-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('branch', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
