# Generated by Django 3.0.4 on 2020-08-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_engineering_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_form',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
