# Generated by Django 3.0.4 on 2020-08-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200803_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_form',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
