# Generated by Django 3.0.4 on 2020-08-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200803_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineering_form',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='engineering_form',
            name='TwelfthPercentage',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineering_form',
            name='applied_for',
            field=models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('NEET-PG', 'NEET-PG'), ('CET', 'CET'), ('COMED-K', 'COMED-K'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='engineering_form',
            name='email',
            field=models.EmailField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact_request',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
