# Generated by Django 3.0.4 on 2020-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200803_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_form',
            name='branch',
            field=models.CharField(max_length=500),
        ),
    ]
