# Generated by Django 3.0.4 on 2020-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200803_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('TwelfthPercentage', models.CharField(max_length=10)),
                ('applied_for', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('NEET-PG', 'NEET-PG'), ('CET', 'CET'), ('COMED-K', 'COMED-K'), ('Other', 'Other')], default='Other', max_length=10)),
                ('branch', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
