# Generated by Django 3.0.4 on 2020-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pgmedical_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architecture_form',
            old_name='applied_for',
            new_name='applied_for_NATA',
        ),
    ]
