# Generated by Django 3.0.9 on 2020-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200803_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawManagementCommerce_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('TwelfthPercentage', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('anyEntrance', models.BooleanField(default=False)),
                ('Law_Management_or_Commerce', models.CharField(default='NA', max_length=15)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
