# Generated by Django 3.0.9 on 2020-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_lawmanagementcommerce_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ph', models.CharField(max_length=12)),
                ('courseType', models.CharField(choices=[('BE / B.Tech', 'BE / B.Tech'), ('Degree', 'Degree'), ('Paramedical', 'Paramedical'), ('Medical', 'Medical'), ('Architecture', 'Architecture')], max_length=15)),
                ('Entrance', models.CharField(choices=[('K-CET 2020', 'K-CET 2020'), ('COMED-K2020', 'COMED-K2020'), ('NEET2020', 'NEET2020'), ('JEE Mains 2020', 'JEE Mains 2020'), ('JEE Advance 2020', 'JEE Advance 2020'), ('Other', 'Other')], default='Other', max_length=20)),
                ('TwelfthPercentage', models.CharField(max_length=10)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('admissionType', models.CharField(choices=[('Counselling', 'Counselling'), ('Direct Admissions', 'Direct Admissions')], max_length=20)),
            ],
        ),
    ]
