# Generated by Django 3.0.9 on 2021-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rankpredictor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAddmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('FormType', models.CharField(choices=[('Career', 'Career'), ('Addmission', 'Addmission')], max_length=50)),
                ('Details', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
